[package]
name = "nft_on_rgb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rgb-lib = "0.1.9"
tempfile = "3.8.1"
